version: "3.9"
services:
    injestor:
        build: .
        volumes:
            - ./private-compose-config.yml:/etc/datainjestor/config.yml
        environment:
            - DATAINJESTOR_VERBOSE_LOGGING=1
            - DATAINJESTOR_CONFIG_FILE=/etc/datainjestor/config.yml
            - CONFIGOR_SQL_CONNECTION=postgresql://postgres:Password123@sql/postgres
            - CONFIGOR_MONGODB_CONNECTION=mongodb://mongo:Password123@mongo:27017?authSource=admin
            - CONFIGOR_MONGODB_DATABASENAME=housing
        depends_on: 
            - sql
        ports:
            - 9090:9090
        restart: on-failure
    sql:
        image: postgres:9.6.22
        environment: 
            - POSTGRES_PASSWORD=Password123
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - sqldata:/var/lib/postgresql/data/pgdata
            - ./db-scripts/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    mongo:
        image: mongo
        restart: always
        environment:
            - MONGO_INITDB_ROOT_USERNAME=mongo
            - MONGO_INITDB_ROOT_PASSWORD=Password123
volumes:
    sqldata: {}