apiVersion: v1
kind: Service
metadata:
  name: datainjestor-svc
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app:  datainjestor
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.port }}