CREATE TABLE Stocks (
    ID serial PRIMARY KEY,
    Symbol varchar(10) NOT NULL,
    "Timestamp" TIMESTAMP NOT NULL,
    OpenPrice numeric(12,2) NOT NULL,
    HighPrice numeric(12,2) NOT NULL,
    LowPrice numeric(12,2) NOT NULL,
    ClosePrice numeric(12,2) NOT NULL,
    Volume numeric(12,2) NOT NULL
);

CREATE TABLE Treasury (
    ID serial PRIMARY KEY,
    "Timestamp" TIMESTAMP NOT NULL,
    Month1 numeric(6,2) NOT NULL,
    Month2 numeric(6,2) NOT NULL,
    Month3 numeric(6,2) NOT NULL,
    Month6 numeric(6,2) NOT NULL,
    Year1 numeric(6,2) NOT NULL,
    Year2 numeric(6,2) NOT NULL,
    Year3 numeric(6,2) NOT NULL,
    Year5 numeric(6,2) NOT NULL,
    Year7 numeric(6,2) NOT NULL,
    Year10 numeric(6,2) NOT NULL,
    Year20 numeric(6,2) NOT NULL,
    Year30 numeric(6,2) NOT NULL
);

CREATE TABLE ShortInterest(
    ID serial PRIMARY KEY,
    Symbol varchar(10) NOT NULL,
    ShortInterest bigint NOT NULL,
    ShortDate TIMESTAMP NOT NULL,
    StockFloat bigint NOT NULL,
    FloatShorted numeric(6,2)
);

CREATE TABLE SingleFamily(
    ID serial PRIMARY KEY,
    RefPoolID varchar(4),
	LoanID varchar(12),
	MonthlyReportPeriod DATE,
	Channel char(1),
	SellerName varchar(50),
	ServiceName varchar(50),
	MasterServices varchar(10),
	OriginalInterestRate numeric(12,2),
	CurrentInterestRate numeric(12,2),
	OriginalUPB numeric(12,2),
	UPBAtIssuance numeric(12,2),
	CurrentActualUPB numeric(12,2),
	OriginalLoanTerm  int,
	OriginationDate DATE,
	FirstPaymentDate DATE,
	LoanAge int,
	RemainingMonthsLegalMaturity int,
	RemainingMonthsMaturity int,
	MaturityDate DATE,
	OriginalLoanTVR int,
	OriginalCombinedLoanTVR int,
	NumberBorrowers int,
	DebtToIncome int,
	BorrowerCSOriginator int,
	CoBorrowerCSOriginator int,
	FirstTimeHomeBuyer char(1),
	LoanPurpose char(1),
	PropertyType char(2),
	NumberOfUnits int,
	OccupancyStatus char(1),
	PropertyState char(2),
	MSA char(5),
	ZipCodeShort char(3),
	MortgageInsurancePercent numeric(5,2),
	AmortizationType char(3),
	PrepaymentPenalty char(1),
	InterestOnlyLoad char(1),
	InterestOnlyFPInterestPD DATE,
	MonthsToAmortization int,
	CurrentLoanDS char(2),
	LoanPaymentHistory varchar(48),
	ModificationFlag char(1),
	MortgageInsuranceCancellation char(2),
	ZeroBalanceCode char(3),
	ZeroBalanceEffectiveDate DATE,
	UPBTimeOfRemoval int,
	RepurchaseDate DATE,
	ScheduledPrincipalCurrent numeric(12,2),
	TotalPrincipalCurrent numeric(12,2),
	UnscheduledPrincipalCurrent numeric(12,2),
	LastPaidInstallmentDate DATE,
	ForeclosureDate DATE,
	DispositionDate DATE,
	ForeclosureCosts numeric(12,2),
	PropertyPreservationRepairCosts numeric(12,2),
	AssetRecoveryCosts numeric(12,2),
	MiscellaneousHoldingExpensesCredit numeric(12,2),
	AssociatedTaxesHoldingProperty numeric(12,2),
	NetSalesProceeds numeric(12,2),
	CreditEnhancementProceeds numeric(12,2),
	RepurchaseMakeWholeProceeds numeric(12,2),
	OtherForeclosureProceeds numeric(12,2),
	NonInterestBearingUPB numeric(12,2),
	PrincipalForgivenessAmount numeric(12,2),
	OriginalListStartDate DATE,
	OriginalListPrice numeric(12,2),
	CurrentListStartDate DATE,
	CurrentListPrice numeric(12,2),
	BorrowCSIssuance int,
	CoBorrowCSIssuance int,
	BorrowCSCurrent int,
	CoBorrowCSCurrent int,
	MortgageIssuranceType char(1),
	ServicingActivity char(1),
	CurrentPeriodModificationLossAmount numeric(12,2),
	CumulativeModificationLossAmount numeric(12,2),
	CurrentPeriodCreditEventNetGainLoss numeric(12,2),
	CumulativeCreditEventNetGainLoss numeric(12,2),
	HomeReadyPI char(1),
	ForeclosurePrincipalWriteOffAmount numeric(12,2),
	RelocationMortgage char(1),
	ZeroBalanceCodeChangeDate DATE,
	LoanHoldback char(1),
	LoanHoldbackEffectiveDate DATE,
	DelinguentAccruedInterest numeric(12,2),
	PropertyValuationMethod char(1),
	HighBalanceLoan char(1),
	ARMInitialFixedRatePeriod char(1),
	ARMProductType  varchar(100),
	InitialFixedRatePeriod int,
	InterestRateAdjustmentFrequency int,
	NextInterestRateAdjustmentDate DATE,
	NextPaymentChangeDate DATE,
	"Index"  varchar(100),
	ARMCapStructure varchar(10),
	InitialInterestRateCapUpPercent numeric(6,4),
	PeriodicInterestRateCapUpPercent numeric(6,4),
	LifetimeInterestRateCapUp numeric(6,4),
	MortgageMargin numeric(6,4),
	ARMBalloon char(1),
	ARMPlanNumber int,
	BorrowerAssistancePlan char(1),
	HighLoanToValueRefinance char(1),
	DealName varchar(200),
	RepurchaseMakeWholeProceedsFlag char(1),
	AlternativeDelinquency char(1),
	AlternativeDelinquencyResolution int,
	TotalDeferralAmount numeric(12,2)
);